package builtin

import "github.com/JadenRazo/llm-lint/internal/rules"

func init() {
	rules.Register(rules.Rule{
		ID:       "LLM013",
		Title:    "AI refusal/boilerplate string in source",
		Severity: rules.SevInfo,
		Category: rules.CatGeneric,
		Kind:     rules.KindContent,
		ContentPatterns: []string{
			`(?i)\bas an AI language model\b`,
			`(?i)\bI cannot fulfill that request\b`,
			`(?i)\bI'm sorry, but I can't\b`,
			`(?i)\bI cannot help with that\b`,
		},
		AutoFix:     rules.AutoFix{RemoveLine: true},
		Description: "Telltale LLM refusal text accidentally pasted into source.",
		Remediation: "Remove the offending text. If this is a fixture or a test of refusal handling, add the path to your `.llmlint.yaml` ignore list.",
	})

	rules.Register(rules.Rule{
		ID:       "LLM014",
		Title:    "AI generation marker in comment",
		Severity: rules.SevInfo,
		Category: rules.CatGeneric,
		Kind:     rules.KindContent,
		ContentPatterns: []string{
			`(?i)Generated by (ChatGPT|GPT-4|GPT-5|GitHub Copilot|Claude(\s+Code)?)\b`,
			`(?i)This (file|code) was generated by (ChatGPT|GPT|Claude|Copilot)\b`,
		},
		AutoFix:     rules.AutoFix{RemoveLine: true},
		Description: "Source file declares itself AI-generated.",
		Remediation: "If intentional, add the path to your `.llmlint.yaml` ignore list. Otherwise remove the marker.",
	})

	rules.Register(rules.Rule{
		ID:       "LLM015",
		Title:    "claude-code MCP referenced in .mcp.json",
		Severity: rules.SevInfo,
		Category: rules.CatClaude,
		Kind:     rules.KindContent,
		ContentPathGlobs: []string{
			".mcp.json",
			"**/.mcp.json",
		},
		ContentPatterns: []string{
			`(?i)\bclaude[-_ ]?code\b`,
			`(?i)@anthropic-ai/claude-code\b`,
		},
		Description: "A repo-level .mcp.json references Claude Code MCP servers. If it pins local paths or secrets, it should not ship.",
		Remediation: "Review the file. If it contains local-only paths or refs, move that config to `.claude/` (which should already be gitignored) or scrub the local values.",
	})
}
