package scanner_test

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/JadenRazo/llm-lint/internal/rules"
	"github.com/JadenRazo/llm-lint/internal/scanner"

	_ "github.com/JadenRazo/llm-lint/internal/rules/builtin"
)

// FuzzContentRuleScan feeds arbitrary file contents through the content-rule
// pipeline and asserts the scanner never panics. The targets here are the
// per-line regex match loop, the binary sniff, and the snippet truncator —
// all of which historically have been sources of off-by-ones and slice-OOB
// bugs in scanners.
//
// Run locally:
//
//	go test ./internal/scanner -fuzz=FuzzContentRuleScan -fuzztime=30s
func FuzzContentRuleScan(f *testing.F) {
	seeds := [][]byte{
		[]byte(""),
		[]byte("\n"),
		[]byte("\x00\x00\x00binary"),
		[]byte("as an AI language model"),
		[]byte("Generated by ChatGPT\nGenerated by Claude Code"),
		[]byte("\r\n\r\n"),
		// extremely long line, no newline, to exercise the truncator
		make([]byte, 2048),
		// long line that contains a match buried inside trailing junk
		append([]byte("padding "), append([]byte("As an AI language model"), make([]byte, 4096)...)...),
	}
	for _, s := range seeds {
		f.Add(s)
	}

	f.Fuzz(func(t *testing.T, data []byte) {
		root := t.TempDir()
		if err := os.WriteFile(filepath.Join(root, "input.txt"), data, 0o644); err != nil {
			t.Fatal(err)
		}
		cfg := &testCfg{}
		s, err := scanner.New(cfg, rules.DefaultRegistry())
		if err != nil {
			t.Fatal(err)
		}
		// Goal: must not panic. We don't assert on matches; the regex behavior
		// is locked by table tests elsewhere.
		_, _, _ = s.Scan(root)
	})
}
