package engine_test

import (
	"os"
	"path/filepath"
	"sort"
	"testing"
	"time"

	"github.com/go-git/go-git/v5"
	"github.com/go-git/go-git/v5/plumbing/object"

	"github.com/JadenRazo/llm-lint/internal/config"
	"github.com/JadenRazo/llm-lint/internal/engine"
	"github.com/JadenRazo/llm-lint/internal/rules"

	_ "github.com/JadenRazo/llm-lint/internal/rules/builtin"
)

// TestEngine_E2E_EveryRule exhaustively exercises every registered rule
// (LLM001..LLM015) against a fixture that contains exactly the artifact
// each rule is supposed to detect, plus near-miss negatives that must NOT
// trigger. This is the load-bearing regression gate: a new rule that
// silently regresses (e.g. a glob that no longer matches) shows up here
// rather than as a missed detection in production.
func TestEngine_E2E_EveryRule(t *testing.T) {
	root := t.TempDir()

	// --- Positive fixtures (must trigger the named rule) -------------------
	files := map[string]string{
		// LLM001 — CLAUDE.md
		"CLAUDE.md": "context\n",
		// LLM002 — .claude/ tracked
		".claude/settings.json": "{}\n",
		// LLM005 — Claude scratchpads (CLAUDE_NOTES.md, CLAUDE_*.md, .claude.local.md)
		"CLAUDE_NOTES.md": "scratch\n",
		// LLM006 — .cursorrules and .cursor/
		".cursorrules":          "rule\n",
		".cursor/settings.json": "{}\n",
		// LLM007 — Copilot config
		".github/copilot-instructions.md": "instructions\n",
		// LLM008 — Aider artifacts
		".aider.conf.yml":        "model: x\n",
		".aider.chat.history.md": "log\n",
		// LLM009 — Continue config
		".continuerc.json":   "{}\n",
		".continue/settings": "{}\n",
		// LLM010 — Codeium
		"codeium.toml":            "key = 1\n",
		".codeium/cache/data.bin": "data\n",
		// LLM011 — Windsurf
		".windsurfrules":       "rule\n",
		".windsurf/state.json": "{}\n",
		// LLM015 — claude-code MCP
		".mcp.json": `{"mcpServers":{"claude-code":{"command":"claude-code"}}}`,

		// LLM013 — refusal text in source
		"src/handler.py": "def f():\n    # As an AI language model, I cannot fulfill that request.\n    pass\n",
		// LLM014 — generation marker
		"src/gen.py": "# Generated by ChatGPT\nimport sys\n",

		// --- Near-miss negatives (must NOT trigger anything) ---------------
		// LLM001 negative: lowercase-only "claude.md" is matched by glob too,
		// so substitute a non-matching name.
		"docs/notes-on-claude.md": "not a CLAUDE.md\n",
		// LLM002 negative: a path containing "claude" but not in a `.claude/` dir.
		"src/claude/handler.go": "package claude\n",
		// LLM005 negative: file name without the CLAUDE_ prefix.
		"docs/notes.md": "regular notes\n",
		// LLM006 negative: file mentions "cursor" without being a cursor config.
		"src/cursor.go": "package cursor\n",
		// LLM007 negative: dependabot lives under .github but is not a copilot file.
		"src/legit.go": "package main\n",
		// LLM008 negative: aider name without leading dot.
		"docs/aider-notes.md": "writing about aider\n",
		// LLM010 negative: codeium mention in a regular source file.
		"src/codeium_client.go": "package codeium\n",
		// LLM015 negative: unrelated MCP files, including a .mcp.json without Claude Code.
		"docs/mcp_config.json": `{"unrelated":true}`,
		"tools/.mcp.json":      `{"mcpServers":{"local-dev":{"command":"dev-server"}}}`,

		// engine config: ignore vendor + testdata so the fixture stays clean
		".llmlint.yaml": "version: 1\nignore:\n  - vendor/**\n  - testdata/**\n",
	}
	for rel, content := range files {
		full := filepath.Join(root, rel)
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	// Init git and craft commits that exercise the trailer/message rules
	// (LLM003, LLM004, LLM012).
	repo, err := git.PlainInit(root, false)
	if err != nil {
		t.Fatal(err)
	}
	wt, err := repo.Worktree()
	if err != nil {
		t.Fatal(err)
	}
	stage := func(rel, body string) {
		if err := os.WriteFile(filepath.Join(root, rel), []byte(body), 0o644); err != nil {
			t.Fatal(err)
		}
		if _, err := wt.Add(rel); err != nil {
			t.Fatal(err)
		}
	}

	// Commit 1: clean baseline
	stage("marker.txt", "1\n")
	if _, err := wt.Commit("chore: init\n", &git.CommitOptions{
		Author: &object.Signature{Name: "Eve", Email: "eve@example.com", When: time.Now()},
	}); err != nil {
		t.Fatal(err)
	}

	// Commit 2: LLM003 (Claude trailer) + LLM004 (message footer)
	stage("marker.txt", "2\n")
	if _, err := wt.Commit(
		"feat: a thing\n\nbody line\n\n"+
			"\xf0\x9f\xa4\x96 Generated with [Claude Code](https://claude.com/code)\n\n"+
			"Co-Authored-By: Claude <noreply@anthropic.com>\n",
		&git.CommitOptions{
			Author: &object.Signature{Name: "Alice", Email: "alice@example.com", When: time.Now().Add(time.Second)},
		},
	); err != nil {
		t.Fatal(err)
	}

	// Commit 3: LLM012 (Copilot trailer)
	stage("marker.txt", "3\n")
	if _, err := wt.Commit(
		"feat: another\n\nCo-authored-by: GitHub Copilot <copilot@github.com>\n",
		&git.CommitOptions{
			Author: &object.Signature{Name: "Bob", Email: "bob@example.com", When: time.Now().Add(2 * time.Second)},
		},
	); err != nil {
		t.Fatal(err)
	}

	cfg, err := config.Load(".llmlint.yaml", root)
	if err != nil {
		t.Fatal(err)
	}
	eng := engine.New(rules.DefaultRegistry(), cfg)
	res, err := eng.Run(root)
	if err != nil {
		t.Fatal(err)
	}

	got := map[string]int{}
	for _, f := range res.Findings {
		got[f.RuleID]++
	}

	// Every documented rule must produce >= 1 finding from this fixture.
	for _, id := range []string{
		"LLM001", "LLM002", "LLM003", "LLM004", "LLM005",
		"LLM006", "LLM007", "LLM008", "LLM009", "LLM010",
		"LLM011", "LLM012", "LLM013", "LLM014", "LLM015",
	} {
		if got[id] == 0 {
			ids := make([]string, 0, len(got))
			for k, v := range got {
				ids = append(ids, k+":"+itoa(v))
			}
			sort.Strings(ids)
			t.Errorf("rule %s produced no finding; got=%v", id, ids)
		}
	}
}

// TestEngine_E2E_NegativeFixtures asserts zero findings on a corpus of
// near-miss filenames and contents that historically have caused false
// positives. Pins the "no surprise hits" contract.
func TestEngine_E2E_NegativeFixtures(t *testing.T) {
	root := t.TempDir()
	files := map[string]string{
		// LLM001/LLM005: filenames that mention "claude" but don't match the globs
		"docs/about-claude.md":  "third-party doc\n",
		"src/claude_handler.go": "package claude\n",
		// LLM006: "cursorrules" without the leading dot is not a Cursor config
		"docs/cursorrules.md": "discussion of cursor rules\n",
		// LLM007: .github file that is not a copilot config
		".github/dependabot.yml": "version: 2\n",
		// LLM008: ".aider" near-miss without dot prefix
		"docs/aider-tutorial.md": "guide to aider\n",
		// LLM015: similar-but-different file name
		"docs/mcp.json": `{"servers":{}}`,
		// Generic: real source code that mentions LLM-y phrases in comments
		"src/main.go": "package main\n// reasonable code without trigger phrases\n",
		// readme is excluded by ignore but include here for completeness
		"README.md":     "# project\n",
		".llmlint.yaml": "version: 1\nignore:\n  - README.md\n",
	}
	for rel, content := range files {
		full := filepath.Join(root, rel)
		if err := os.MkdirAll(filepath.Dir(full), 0o755); err != nil {
			t.Fatal(err)
		}
		if err := os.WriteFile(full, []byte(content), 0o644); err != nil {
			t.Fatal(err)
		}
	}

	// Init git with a clean commit so the gitscan branch runs and finds nothing.
	repo, err := git.PlainInit(root, false)
	if err != nil {
		t.Fatal(err)
	}
	wt, err := repo.Worktree()
	if err != nil {
		t.Fatal(err)
	}
	if _, err := wt.Add("src/main.go"); err != nil {
		t.Fatal(err)
	}
	if _, err := wt.Commit(
		"feat: clean\n\nSigned-off-by: Eve <eve@example.com>\n",
		&git.CommitOptions{Author: &object.Signature{Name: "Eve", Email: "eve@example.com", When: time.Now()}},
	); err != nil {
		t.Fatal(err)
	}

	cfg, err := config.Load(".llmlint.yaml", root)
	if err != nil {
		t.Fatal(err)
	}
	eng := engine.New(rules.DefaultRegistry(), cfg)
	res, err := eng.Run(root)
	if err != nil {
		t.Fatal(err)
	}
	if len(res.Findings) != 0 {
		ids := make([]string, 0, len(res.Findings))
		for _, f := range res.Findings {
			ids = append(ids, f.RuleID+"/"+f.Location.Path)
		}
		sort.Strings(ids)
		t.Errorf("expected zero findings on near-miss corpus; got %d:\n%v", len(res.Findings), ids)
	}
}

func itoa(i int) string {
	if i == 0 {
		return "0"
	}
	neg := ""
	if i < 0 {
		neg = "-"
		i = -i
	}
	out := ""
	for i > 0 {
		out = string(rune('0'+i%10)) + out
		i /= 10
	}
	return neg + out
}
